[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Include libraries needed for the project
lib_deps = 
    adafruit/Adafruit Unified Sensor@^1.1.14
    adafruit/Adafruit BME280 Library@^2.2.4
    adafruit/Adafruit BusIO@^1.16.1
    sparkfun/SparkFun SCD30 Arduino Library@^1.0.19

build_flags = 
    -DCORE_DEBUG_LEVEL=3
